# Generated by Django 4.0.3 on 2022-03-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='movieitem',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='movieitem',
            name='updated_date',
        ),
    ]
